"""Allow null for room_id

Revision ID: 5a6bd4722c28
Revises: a38392084163
Create Date: 2026-02-16 06:48:30.384408

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a6bd4722c28'
down_revision = 'a38392084163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deviceroomlink')
    op.alter_column('device', 'room_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'room_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.create_table('deviceroomlink',
    sa.Column('device_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('room_id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('deviceroomlink_ibfk_1')),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('deviceroomlink_ibfk_2')),
    sa.PrimaryKeyConstraint('device_id', 'room_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
