"""add_node_type_and_node_tables

Revision ID: 9f1c2d3e4a5b
Revises: 65b53df55f95
Create Date: 2026-07-02

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9f1c2d3e4a5b'
down_revision = '65b53df55f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'node_type',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('parent_type_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(['parent_type_id'], ['node_type.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'rank', name='uq_node_type_tenant_rank'),
    )
    op.create_index(op.f('ix_node_type_tenant_id'), 'node_type', ['tenant_id'], unique=False)

    op.create_table(
        'node',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('node_type_id', sa.Uuid(), nullable=False),
        sa.Column('parent_id', sa.Uuid(), nullable=True),
        sa.Column('path_ids', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['node_type_id'], ['node_type.id']),
        sa.ForeignKeyConstraint(['parent_id'], ['node.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node')
    op.drop_index(op.f('ix_node_type_tenant_id'), table_name='node_type')
    op.drop_table('node_type')
    # ### end Alembic commands ###
