"""add_device_table

Revision ID: d9840a02dbed
Revises: 7488e4fab5f1
Create Date: 2026-07-09 04:54:42.522964

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd9840a02dbed'
down_revision = '7488e4fab5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('addr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_addr'), 'device', ['addr'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_addr'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
